package client

import (
	"context"
	"io"
	"net/url"

	"github.com/alibaba/pouch/apis/types"
)

// ContainerLogs return the logs generated by a container in an io.ReadCloser.
func (client *APIClient) ContainerLogs(ctx context.Context, name string, options types.ContainerLogsOptions) (io.ReadCloser, error) {
	query := url.Values{}
	if options.ShowStdout {
		query.Set("stdout", "1")
	}

	if options.ShowStderr {
		query.Set("stderr", "1")
	}

	if options.Since != "" {
		// TODO
	}

	if options.Until != "" {
		// TODO
	}

	if options.Timestamps {
		query.Set("timestamps", "1")
	}

	if options.Details {
		query.Set("details", "1")
	}

	if options.Follow {
		query.Set("follow", "1")
	}
	query.Set("tail", options.Tail)

	resp, err := client.get(ctx, "/containers/"+name+"/logs", query, nil)
	if err != nil {
		return nil, err
	}
	ensureCloseReader(resp)
	return resp.Body, nil
}
