// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AuthConfig auth config
// swagger:model AuthConfig

type AuthConfig struct {

	// auth
	Auth string `json:"Auth,omitempty"`

	// IdentityToken is used to authenticate the user and get an access token for the registry
	IdentityToken string `json:"IdentityToken,omitempty"`

	// password
	Password string `json:"Password,omitempty"`

	// RegistryToken is a bearer token to be sent to a registry
	RegistryToken string `json:"RegistryToken,omitempty"`

	// server address
	ServerAddress string `json:"ServerAddress,omitempty"`

	// username
	Username string `json:"Username,omitempty"`
}

/* polymorph AuthConfig Auth false */

/* polymorph AuthConfig IdentityToken false */

/* polymorph AuthConfig Password false */

/* polymorph AuthConfig RegistryToken false */

/* polymorph AuthConfig ServerAddress false */

/* polymorph AuthConfig Username false */

// Validate validates this auth config
func (m *AuthConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *AuthConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthConfig) UnmarshalBinary(b []byte) error {
	var res AuthConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
