// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CheckpointCreateOptions options of creating a checkpoint from a running container, checkpoint is used to restore a container with current state later
// swagger:model CheckpointCreateOptions
type CheckpointCreateOptions struct {

	// checkpoint dir
	CheckpointDir string `json:"CheckpointDir,omitempty"`

	// checkpoint ID
	CheckpointID string `json:"CheckpointID,omitempty"`

	// exit
	Exit bool `json:"Exit,omitempty"`
}

// Validate validates this checkpoint create options
func (m *CheckpointCreateOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CheckpointCreateOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CheckpointCreateOptions) UnmarshalBinary(b []byte) error {
	var res CheckpointCreateOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
