// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Checkpoint describe a created checkpoint, include container name and checkpoint name
// swagger:model Checkpoint
type Checkpoint struct {

	// checkpoint name
	CheckpointName string `json:"CheckpointName,omitempty"`

	// container ID
	ContainerID string `json:"ContainerID,omitempty"`
}

// Validate validates this checkpoint
func (m *Checkpoint) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Checkpoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Checkpoint) UnmarshalBinary(b []byte) error {
	var res Checkpoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
