// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContainerStartOptions options of starting container
// swagger:model ContainerStartOptions

type ContainerStartOptions struct {

	// checkpoint dir
	CheckpointDir string `json:"CheckpointDir,omitempty"`

	// checkpoint ID
	CheckpointID string `json:"CheckpointID,omitempty"`

	// detach keys
	DetachKeys string `json:"DetachKeys,omitempty"`
}

/* polymorph ContainerStartOptions CheckpointDir false */

/* polymorph ContainerStartOptions CheckpointID false */

/* polymorph ContainerStartOptions DetachKeys false */

// Validate validates this container start options
func (m *ContainerStartOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ContainerStartOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerStartOptions) UnmarshalBinary(b []byte) error {
	var res ContainerStartOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
