// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContainerExecInspect holds information about a running process started.
// swagger:model ContainerExecInspect

type ContainerExecInspect struct {

	// can remove
	CanRemove bool `json:"CanRemove,omitempty"`

	// The ID of this container
	ContainerID string `json:"ContainerID,omitempty"`

	// detach keys
	DetachKeys string `json:"DetachKeys,omitempty"`

	// The last exit code of this container
	ExitCode int64 `json:"ExitCode,omitempty"`

	// The ID of this exec
	ID string `json:"ID,omitempty"`

	// open stderr
	OpenStderr bool `json:"OpenStderr,omitempty"`

	// open stdin
	OpenStdin bool `json:"OpenStdin,omitempty"`

	// open stdout
	OpenStdout bool `json:"OpenStdout,omitempty"`

	// process config
	ProcessConfig *ProcessConfig `json:"ProcessConfig,omitempty"`

	// running
	Running bool `json:"Running,omitempty"`
}

/* polymorph ContainerExecInspect CanRemove false */

/* polymorph ContainerExecInspect ContainerID false */

/* polymorph ContainerExecInspect DetachKeys false */

/* polymorph ContainerExecInspect ExitCode false */

/* polymorph ContainerExecInspect ID false */

/* polymorph ContainerExecInspect OpenStderr false */

/* polymorph ContainerExecInspect OpenStdin false */

/* polymorph ContainerExecInspect OpenStdout false */

/* polymorph ContainerExecInspect ProcessConfig false */

/* polymorph ContainerExecInspect Running false */

// Validate validates this container exec inspect
func (m *ContainerExecInspect) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProcessConfig(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContainerExecInspect) validateProcessConfig(formats strfmt.Registry) error {

	if swag.IsZero(m.ProcessConfig) { // not required
		return nil
	}

	if m.ProcessConfig != nil {

		if err := m.ProcessConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ProcessConfig")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ContainerExecInspect) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerExecInspect) UnmarshalBinary(b []byte) error {
	var res ContainerExecInspect
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
