// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DaemonUpdateConfig daemon update config
// swagger:model DaemonUpdateConfig

type DaemonUpdateConfig struct {

	// Image proxy used to pull image.
	ImageProxy string `json:"ImageProxy,omitempty"`

	// Labels indentified the attributes of daemon
	Labels []string `json:"Labels"`
}

/* polymorph DaemonUpdateConfig ImageProxy false */

/* polymorph DaemonUpdateConfig Labels false */

// Validate validates this daemon update config
func (m *DaemonUpdateConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLabels(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DaemonUpdateConfig) validateLabels(formats strfmt.Registry) error {

	if swag.IsZero(m.Labels) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DaemonUpdateConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DaemonUpdateConfig) UnmarshalBinary(b []byte) error {
	var res DaemonUpdateConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
