// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DeviceMapping A device mapping between the host and container
// swagger:model DeviceMapping

type DeviceMapping struct {

	// cgroup permissions of the device
	CgroupPermissions string `json:"CgroupPermissions,omitempty"`

	// path in container of the device mapping
	PathInContainer string `json:"PathInContainer,omitempty"`

	// path on host of the device mapping
	PathOnHost string `json:"PathOnHost,omitempty"`
}

/* polymorph DeviceMapping CgroupPermissions false */

/* polymorph DeviceMapping PathInContainer false */

/* polymorph DeviceMapping PathOnHost false */

// Validate validates this device mapping
func (m *DeviceMapping) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DeviceMapping) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceMapping) UnmarshalBinary(b []byte) error {
	var res DeviceMapping
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
