// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// EndpointIPAMConfig IPAM configurations for the endpoint
// swagger:model EndpointIPAMConfig

type EndpointIPAMConfig struct {

	// ipv4 address
	IPV4Address string `json:"IPv4Address,omitempty"`

	// ipv6 address
	IPV6Address string `json:"IPv6Address,omitempty"`

	// link to the list of local ip
	LinkLocalIps []string `json:"LinkLocalIPs"`
}

/* polymorph EndpointIPAMConfig IPv4Address false */

/* polymorph EndpointIPAMConfig IPv6Address false */

/* polymorph EndpointIPAMConfig LinkLocalIPs false */

// Validate validates this endpoint IP a m config
func (m *EndpointIPAMConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLinkLocalIps(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EndpointIPAMConfig) validateLinkLocalIps(formats strfmt.Registry) error {

	if swag.IsZero(m.LinkLocalIps) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EndpointIPAMConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EndpointIPAMConfig) UnmarshalBinary(b []byte) error {
	var res EndpointIPAMConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
