// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ExecCreateResp contains response of Remote API POST "/containers/{name:.*}/exec".
// swagger:model ExecCreateResp

type ExecCreateResp struct {

	// ID is the exec ID
	ID string `json:"Id,omitempty"`
}

/* polymorph ExecCreateResp Id false */

// Validate validates this exec create resp
func (m *ExecCreateResp) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ExecCreateResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExecCreateResp) UnmarshalBinary(b []byte) error {
	var res ExecCreateResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
