// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExecStartConfig ExecStartConfig is a temp struct used by execStart.
// swagger:model ExecStartConfig
type ExecStartConfig struct {

	// Config the started exec process inside the container detached from the client.
	// For example, if set to be true, the CLI command line will be detached from
	// the exec processes's stdin/stdout/stderr stream, and command will terminated
	// at once while the exec process will be running background in container.
	//
	Detach bool `json:"Detach,omitempty"`

	// Config the exec start whether to allocate a pseudo-TTY.
	Tty bool `json:"Tty,omitempty"`
}

// Validate validates this exec start config
func (m *ExecStartConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExecStartConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExecStartConfig) UnmarshalBinary(b []byte) error {
	var res ExecStartConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
