// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ImagePruneResp ImagePruneResponse
//
// response returned by daemon when unused images were removed
// swagger:model ImagePruneResp
type ImagePruneResp struct {

	// Images that were deleted
	ImagesDeleted []*ImageDeleteRespItem `json:"ImagesDeleted"`

	// Disk space reclaimed in bytes
	SpaceReclaimed int64 `json:"SpaceReclaimed,omitempty"`
}

// Validate validates this image prune resp
func (m *ImagePruneResp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateImagesDeleted(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImagePruneResp) validateImagesDeleted(formats strfmt.Registry) error {

	if swag.IsZero(m.ImagesDeleted) { // not required
		return nil
	}

	for i := 0; i < len(m.ImagesDeleted); i++ {
		if swag.IsZero(m.ImagesDeleted[i]) { // not required
			continue
		}

		if m.ImagesDeleted[i] != nil {
			if err := m.ImagesDeleted[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ImagesDeleted" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImagePruneResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImagePruneResp) UnmarshalBinary(b []byte) error {
	var res ImagePruneResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
