// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ImageInfo An object containing all details of an image at API side
// swagger:model ImageInfo

type ImageInfo struct {

	// Time of image creation
	CreatedAt string `json:"CreatedAt,omitempty"`

	// digest of image.
	Digest string `json:"Digest,omitempty"`

	// ID of an image.
	ID string `json:"ID,omitempty"`

	// name of an image.
	Name string `json:"Name,omitempty"`

	// size of image's taking disk space.
	Size int64 `json:"Size,omitempty"`

	// tag of an image.
	Tag string `json:"Tag,omitempty"`
}

/* polymorph ImageInfo CreatedAt false */

/* polymorph ImageInfo Digest false */

/* polymorph ImageInfo ID false */

/* polymorph ImageInfo Name false */

/* polymorph ImageInfo Size false */

/* polymorph ImageInfo Tag false */

// Validate validates this image info
func (m *ImageInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ImageInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageInfo) UnmarshalBinary(b []byte) error {
	var res ImageInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
