// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// MountPoint A mount point inside a container
// swagger:model MountPoint

type MountPoint struct {

	// copy data
	CopyData bool `json:"CopyData,omitempty"`

	// destination
	Destination string `json:"Destination,omitempty"`

	// driver
	Driver string `json:"Driver,omitempty"`

	// ID
	ID string `json:"ID,omitempty"`

	// mode
	Mode string `json:"Mode,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// named
	Named bool `json:"Named,omitempty"`

	// propagation
	Propagation string `json:"Propagation,omitempty"`

	// r w
	RW bool `json:"RW,omitempty"`

	// replace
	Replace string `json:"Replace,omitempty"`

	// source
	Source string `json:"Source,omitempty"`

	// type
	Type string `json:"Type,omitempty"`
}

/* polymorph MountPoint CopyData false */

/* polymorph MountPoint Destination false */

/* polymorph MountPoint Driver false */

/* polymorph MountPoint ID false */

/* polymorph MountPoint Mode false */

/* polymorph MountPoint Name false */

/* polymorph MountPoint Named false */

/* polymorph MountPoint Propagation false */

/* polymorph MountPoint RW false */

/* polymorph MountPoint Replace false */

/* polymorph MountPoint Source false */

/* polymorph MountPoint Type false */

// Validate validates this mount point
func (m *MountPoint) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *MountPoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MountPoint) UnmarshalBinary(b []byte) error {
	var res MountPoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
