// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// NetworkCreateConfig contains the request for the remote API: POST /networks/create
// swagger:model NetworkCreateConfig

type NetworkCreateConfig struct {

	// Name is the name of the network.
	Name string `json:"Name,omitempty"`

	// network create
	NetworkCreate *NetworkCreate `json:"NetworkCreate,omitempty"`
}

/* polymorph NetworkCreateConfig Name false */

/* polymorph NetworkCreateConfig NetworkCreate false */

// Validate validates this network create config
func (m *NetworkCreateConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNetworkCreate(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NetworkCreateConfig) validateNetworkCreate(formats strfmt.Registry) error {

	if swag.IsZero(m.NetworkCreate) { // not required
		return nil
	}

	if m.NetworkCreate != nil {

		if err := m.NetworkCreate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("NetworkCreate")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NetworkCreateConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkCreateConfig) UnmarshalBinary(b []byte) error {
	var res NetworkCreateConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
