// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NetworkSettings NetworkSettings exposes the network settings in the API.
// swagger:model NetworkSettings

type NetworkSettings struct {

	// Name of the network'a bridge (for example, `pouch-br`).
	Bridge string `json:"Bridge,omitempty"`

	// Indicates if hairpin NAT should be enabled on the virtual interface
	HairpinMode bool `json:"HairpinMode,omitempty"`

	// IPv6 unicast address using the link-local prefix
	LinkLocalIPV6Address string `json:"LinkLocalIPv6Address,omitempty"`

	// Prefix length of the IPv6 unicast address.
	LinkLocalIPV6PrefixLen int64 `json:"LinkLocalIPv6PrefixLen,omitempty"`

	// Information about all networks that the container is connected to
	Networks map[string]*EndpointSettings `json:"Networks,omitempty"`

	// ports
	Ports PortMap `json:"Ports,omitempty"`

	// SandboxID uniquely represents a container's network stack.
	SandboxID string `json:"SandboxID,omitempty"`

	// SandboxKey identifies the sandbox
	SandboxKey string `json:"SandboxKey,omitempty"`

	// secondary IP addresses
	SecondaryIPAddresses []*IPAddress `json:"SecondaryIPAddresses"`

	// secondary ipv6 addresses
	SecondaryIPV6Addresses []*IPAddress `json:"SecondaryIPv6Addresses"`
}

/* polymorph NetworkSettings Bridge false */

/* polymorph NetworkSettings HairpinMode false */

/* polymorph NetworkSettings LinkLocalIPv6Address false */

/* polymorph NetworkSettings LinkLocalIPv6PrefixLen false */

/* polymorph NetworkSettings Networks false */

/* polymorph NetworkSettings Ports false */

/* polymorph NetworkSettings SandboxID false */

/* polymorph NetworkSettings SandboxKey false */

/* polymorph NetworkSettings SecondaryIPAddresses false */

/* polymorph NetworkSettings SecondaryIPv6Addresses false */

// Validate validates this network settings
func (m *NetworkSettings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNetworks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSecondaryIPAddresses(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSecondaryIPV6Addresses(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NetworkSettings) validateNetworks(formats strfmt.Registry) error {

	if swag.IsZero(m.Networks) { // not required
		return nil
	}

	if err := validate.Required("Networks", "body", m.Networks); err != nil {
		return err
	}

	return nil
}

func (m *NetworkSettings) validateSecondaryIPAddresses(formats strfmt.Registry) error {

	if swag.IsZero(m.SecondaryIPAddresses) { // not required
		return nil
	}

	for i := 0; i < len(m.SecondaryIPAddresses); i++ {

		if swag.IsZero(m.SecondaryIPAddresses[i]) { // not required
			continue
		}

		if m.SecondaryIPAddresses[i] != nil {

			if err := m.SecondaryIPAddresses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("SecondaryIPAddresses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *NetworkSettings) validateSecondaryIPV6Addresses(formats strfmt.Registry) error {

	if swag.IsZero(m.SecondaryIPV6Addresses) { // not required
		return nil
	}

	for i := 0; i < len(m.SecondaryIPV6Addresses); i++ {

		if swag.IsZero(m.SecondaryIPV6Addresses[i]) { // not required
			continue
		}

		if m.SecondaryIPV6Addresses[i] != nil {

			if err := m.SecondaryIPV6Addresses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("SecondaryIPv6Addresses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *NetworkSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkSettings) UnmarshalBinary(b []byte) error {
	var res NetworkSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
