// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// NetworkCreateResponse contains the response for the remote API: POST /networks/create
// swagger:model NetworkCreateResponse

type NetworkCreateResponse struct {

	// ID is the id of the network.
	ID string `json:"ID,omitempty"`

	// Warning means the message of create network result.
	Warning string `json:"Warning,omitempty"`
}

/* polymorph NetworkCreateResponse ID false */

/* polymorph NetworkCreateResponse Warning false */

// Validate validates this network create response
func (m *NetworkCreateResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *NetworkCreateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkCreateResponse) UnmarshalBinary(b []byte) error {
	var res NetworkCreateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
