// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// NetworkDisconnect Parameters of network disconnect
// swagger:model NetworkDisconnect

type NetworkDisconnect struct {

	// The ID or name of the container to disconnect from the network.
	Container string `json:"Container,omitempty"`

	// Force the container to disconnect from the network.
	Force bool `json:"Force,omitempty"`
}

/* polymorph NetworkDisconnect Container false */

/* polymorph NetworkDisconnect Force false */

// Validate validates this network disconnect
func (m *NetworkDisconnect) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *NetworkDisconnect) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkDisconnect) UnmarshalBinary(b []byte) error {
	var res NetworkDisconnect
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
