// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// NvidiaConfig nvidia config
// swagger:model NvidiaConfig

type NvidiaConfig struct {

	// NvidiaDriverCapabilities controls which driver libraries/binaries will be mounted inside the container
	NvidiaDriverCapabilities string `json:"NvidiaDriverCapabilities,omitempty"`

	// NvidiaVisibleDevices controls which GPUs will be made accessible inside the container
	NvidiaVisibleDevices string `json:"NvidiaVisibleDevices,omitempty"`
}

/* polymorph NvidiaConfig NvidiaDriverCapabilities false */

/* polymorph NvidiaConfig NvidiaVisibleDevices false */

// Validate validates this nvidia config
func (m *NvidiaConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *NvidiaConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NvidiaConfig) UnmarshalBinary(b []byte) error {
	var res NvidiaConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
