// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// PortMap PortMap describes the mapping of container ports to host ports, using the
// container's port-number and protocol as key in the format `<port>/<protocol>`,
// for example, `80/udp`.
//
// If a container's port is mapped for both `tcp` and `udp`, two separate
// entries are added to the mapping table.
//
// swagger:model PortMap

type PortMap map[string][]PortBinding

// Validate validates this port map
func (m PortMap) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", PortMap(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
