// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PortBinding PortBinding represents a binding between a host IP address and a host port
// swagger:model PortBinding

type PortBinding struct {

	// Host IP address that the container's port is mapped to.
	HostIP string `json:"HostIp,omitempty"`

	// Host port number that the container's port is mapped to.
	HostPort string `json:"HostPort,omitempty"`
}

/* polymorph PortBinding HostIp false */

/* polymorph PortBinding HostPort false */

// Validate validates this port binding
func (m *PortBinding) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PortBinding) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PortBinding) UnmarshalBinary(b []byte) error {
	var res PortBinding
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
