// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RestartPolicy Define container's restart policy
// swagger:model RestartPolicy

type RestartPolicy struct {

	// maximum retry count
	MaximumRetryCount int64 `json:"MaximumRetryCount,omitempty"`

	// name
	Name string `json:"Name,omitempty"`
}

/* polymorph RestartPolicy MaximumRetryCount false */

/* polymorph RestartPolicy Name false */

// Validate validates this restart policy
func (m *RestartPolicy) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *RestartPolicy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestartPolicy) UnmarshalBinary(b []byte) error {
	var res RestartPolicy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
