// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Ulimit A list of resource limits
// swagger:model Ulimit

type Ulimit struct {

	// Hard limit
	Hard int64 `json:"Hard,omitempty"`

	// Name of ulimit
	Name string `json:"Name,omitempty"`

	// Soft limit
	Soft int64 `json:"Soft,omitempty"`
}

/* polymorph Ulimit Hard false */

/* polymorph Ulimit Name false */

/* polymorph Ulimit Soft false */

// Validate validates this ulimit
func (m *Ulimit) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Ulimit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Ulimit) UnmarshalBinary(b []byte) error {
	var res Ulimit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
